Repository jenkins-x-plugins/jx-build-controller, pull requests merged in 2020-12, with the labels that each got.

#2 refactor: remove old v2 requirements
  go.mod
  go.sum
  pkg/cmd/controller/controller.go
  pkg/cmd/controller/jx/jx.go
  pkg/cmd/controller/tekton/tekton.go
  pkg/cmd/controller/tekton/tekton_test.go
Labels: approved, size/L

#3 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  .lighthouse/jenkins-x/triggers.yaml
Labels: size/XL, updatebot

#4 fix: long term storage
  go.mod
  go.sum
  pkg/cmd/controller/tekton/tekton.go
Labels: approved, size/L

#5 fix: mount git creds so we can clone requirements from private git repos
  Dockerfile
  charts/jx-build-controller/templates/deployment.yaml
  go.mod
  go.sum
  pkg/cmd/controller/tekton/tekton.go
Labels: approved, size/S
