Repository jenkins-x-plugins/jx-build-controller, pull requests merged in 2021-01, with the labels that each got.

#8 chore: upgrade jx-helpers
  go.mod
Labels: approved, size/XS

#9 feat: add deployment secret env vars
  .gitignore
  charts/jx-build-controller/templates/deployment.yaml
  charts/jx-build-controller/templates/env-secret.yaml
  charts/jx-build-controller/values.yaml
Labels: approved, lgtm, ok-to-test, size/M

#10 fix: bump deps to fix Azure build logs
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/L

#14 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/M, updatebot

#15 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/XS, updatebot

#18 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: updatebot

#11 feat: store the activity in YAML format
  go.mod
  pkg/cmd/controller/tekton/tekton.go
Labels: needs-ok-to-test, size/S

#20 fix: better env var for OpenShift
  charts/jx-build-controller/values.yaml
Labels: approved, size/XS

#21 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/L, updatebot
